# Generated by Django 5.1.2 on 2024-10-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happylife', '0002_days_status_parking_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='happylifeusers',
            name='schedule_ids',
            field=models.ManyToManyField(blank=True, null=True, to='happylife.schedule'),
        ),
    ]
